name: storage_tools
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.19.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  stash: ^4.5.1
  state_notifier: ^0.7.2+1
  tools:
    path: "../tools"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
