name: tools
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^3.0.3
  event_bus: ^2.0.0
  flutter:
    sdk: flutter

  flutter_hooks: ^0.18.5+1
  fpdart: ^0.5.0
  freezed_annotation: ^2.2.0
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.0
  path: ^1.8.1
  path_provider: ^2.0.10
  state_notifier: ^0.7.2+1
  url_launcher: ^6.1.6
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
